In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup as soup

# [SCRAPE MELBOURNE HOUSING FOR RENT ON ZILLOW](https://www.zillow.com/melbourne-fl/rentals/?searchQueryState=%7B%22pagination%22%3A%7B%7D%2C%22usersSearchTerm%22%3A%22Melbourne%2C%20FL%22%2C%22mapBounds%22%3A%7B%22west%22%3A-80.93409468457031%2C%22east%22%3A-80.39439131542969%2C%22south%22%3A27.96619499260209%2C%22north%22%3A28.335500912695093%7D%2C%22regionSelection%22%3A%5B%7B%22regionId%22%3A19307%2C%22regionType%22%3A6%7D%5D%2C%22isMapVisible%22%3Atrue%2C%22filterState%22%3A%7B%22fsba%22%3A%7B%22value%22%3Afalse%7D%2C%22fsbo%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22fr%22%3A%7B%22value%22%3Atrue%7D%2C%22ah%22%3A%7B%22value%22%3Atrue%7D%7D%2C%22isListVisible%22%3Atrue%2C%22mapZoom%22%3A11%7D)

In [2]:
header = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
    'referer': 'https://www.zillow.com/melbourne-fl/rentals/?searchQueryState=%7B%22pagination%22%3A%7B%7D%2C%22usersSearchTerm%22%3A%22Melbourne%2C%20FL%22%2C%22mapBounds%22%3A%7B%22west%22%3A-80.93409468457031%2C%22east%22%3A-80.39439131542969%2C%22south%22%3A27.96619499260209%2C%22north%22%3A28.335500912695093%7D%2C%22regionSelection%22%3A%5B%7B%22regionId%22%3A19307%2C%22regionType%22%3A6%7D%5D%2C%22isMapVisible%22%3Afalse%2C%22filterState%22%3A%7B%22fsba%22%3A%7B%22value%22%3Afalse%7D%2C%22fsbo%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22fr%22%3A%7B%22value%22%3Atrue%7D%2C%22ah%22%3A%7B%22value%22%3Atrue%7D%7D%2C%22isListVisible%22%3Atrue%2C%22mapZoom%22%3A11%7D'
    
}

In [3]:
url = 'https://www.zillow.com/melbourne-fl/rentals'

In [4]:
html = requests.get(url=url,headers=header)
html.status_code

200

In [5]:
bsobj = soup(html.content,'lxml')

In [6]:
price_list = []

for price in bsobj.findAll('div',{'class':'list-card-heading'}):
    price_list.append(price.text.replace('bd','b|').replace('|s','|').replace('o','o|').strip().split('|')[:-1])
price_list

[['$4,300+ Studio', '$3,500+ 1 b', '$4,595+ 2 b', '$5,100+ 3 b'],
 ['$1,575+ 1 b', '$2,040+ 2 b'],
 ['$1,567+ 1 b', '$1,852+ 2 b'],
 ['$1,215+ 1 b', '$1,450+ 2 b', '$1,450+ 3 b'],
 ['$1,935+ 1 b', '$2,488+ 2 b', '$3,403+ 3 b'],
 ['$1,325+ 1 b', '$1,630+ 2 b'],
 ['$1,615+ 1 b', '$1,840+ 2 b', '$2,245+ 3 b'],
 ['$1,385+ 1 b', '$1,810+ 2 b'],
 ['$1,769+ 1 b', '$2,149+ 2 b', '$2,299+ 3 b'],
 []]

In [16]:
image = []

for price in bsobj.findAll('div',{'class':'list-card-top'}):
    price_list.append(price.text.replace('bd','b|').replace('|s','|').replace('o','o|').strip().split('|')[:-1])
image

[]

In [23]:
address = []

for adr in bsobj.findAll('div',{'class':'list-card-info'}):
    address.append(adr.a)

address

[<a class="list-card-link list-card-link-top-margin" href="/b/the-brennity-at-melbourne-melbourne-fl-5Yy4Zx/" tabindex="0"><address class="list-card-addr">The Brennity at Melbourne | 7300 Watersong Ln, Melbourne, FL</address></a>,
 <a class="list-card-link list-card-link-top-margin" href="/b/marisol-at-viera-melbourne-fl-65g3rv/" tabindex="0"><address class="list-card-addr">Marisol at Viera | 2439 Casona Ln, Melbourne, FL</address></a>,
 <a class="list-card-link list-card-link-top-margin" href="/b/the-preserve-at-longleaf-melbourne-fl-5XrSwx/" tabindex="0"><address class="list-card-addr">The Preserve at Longleaf | 4465 Preserve Dr, Melbourne, FL</address></a>,
 <a class="list-card-link list-card-link-top-margin" href="/b/topaz-village-apartments-melbourne-fl-5Xhwzr/" tabindex="0"><address class="list-card-addr">Topaz Village Apartments | 150 E University Blvd, Melbourne, FL</address></a>,
 <a class="list-card-link list-card-link-top-margin" href="/b/centre-pointe-apartments-melbourne-fl-BLYgLP/" tabindex="0"><address class="list-card-addr">Centre Pointe Apartments | 6705 Shadow Creek Trl, Melbourne, FL</address></a>,
 <a class="list-card-link list-card-link-top-margin" href="/b/caribbean-isle-melbourne-fl-5Xhwyc/" tabindex="0"><address class="list-card-addr">Caribbean Isle | 2848 Caribbean Isle Blvd, Melbourne, FL</address></a>,
 <a class="list-card-link list-card-link-top-margin" href="/b/lakes-at-suntree-melbourne-fl-5Xhx65/" tabindex="0"><address class="list-card-addr">Lakes at Suntree | 201 Plantation Club Dr, Melbourne, FL</address></a>,
 <a class="list-card-link list-card-link-top-margin" href="/b/compass-melbourne-fl-5Xhx26/" tabindex="0"><address class="list-card-addr">Compass | 3595 Misty Oak Dr, Melbourne, FL</address></a>,
 <a class="list-card-link list-card-link-top-margin" href="/b/via-tuscany-apartments-melbourne-fl-5Xhx86/" tabindex="0"><address class="list-card-addr">Via Tuscany Apartments | 300 Tuscany Way, Melbourne, FL</address></a>,
 None]

In [8]:
df = pd.DataFrame(price_list,columns=['Price1','Price2','Price3', 'Price4'])
df

           Price1       Price2       Price3       Price4
0  $4,300+ Studio  $3,500+ 1 b  $4,595+ 2 b  $5,100+ 3 b
1     $1,575+ 1 b  $2,040+ 2 b         None         None
2     $1,567+ 1 b  $1,852+ 2 b         None         None
3     $1,215+ 1 b  $1,450+ 2 b  $1,450+ 3 b         None
4     $1,935+ 1 b  $2,488+ 2 b  $3,403+ 3 b         None
5     $1,325+ 1 b  $1,630+ 2 b         None         None
6     $1,615+ 1 b  $1,840+ 2 b  $2,245+ 3 b         None
7     $1,385+ 1 b  $1,810+ 2 b         None         None
8     $1,769+ 1 b  $2,149+ 2 b  $2,299+ 3 b         None
9            None         None         None         None

In [9]:
df['Address'] = address
df

,Price1,Price2,Price3,Price4,Address
0,"$4,300+ Studio","$3,500+ 1 b","$4,595+ 2 b","$5,100+ 3 b",[[The Brennity at Melbourne | 7300 Watersong L...
1,"$1,575+ 1 b","$2,040+ 2 b",None,None,"[[Marisol at Viera | 2439 Casona Ln, Melbourne..."
2,"$1,567+ 1 b","$1,852+ 2 b",None,None,"[[The Preserve at Longleaf | 4465 Preserve Dr,..."
3,"$1,215+ 1 b","$1,450+ 2 b","$1,450+ 3 b",None,[[Topaz Village Apartments | 150 E University ...
4,"$1,935+ 1 b","$2,488+ 2 b","$3,403+ 3 b",None,[[Centre Pointe Apartments | 6705 Shadow Creek...
5,"$1,325+ 1 b","$1,630+ 2 b",None,None,"[[Caribbean Isle | 2848 Caribbean Isle Blvd, M..."
6,"$1,615+ 1 b","$1,840+ 2 b","$2,245+ 3 b",None,"[[Lakes at Suntree | 201 Plantation Club Dr, M..."
7,"$1,385+ 1 b","$1,810+ 2 b",None,None,"[[Compass | 3595 Misty Oak Dr, Melbourne, FL]]"
8,"$1,769+ 1 b","$2,149+ 2 b","$2,299+ 3 b",None,"[[Via Tuscany Apartments | 300 Tuscany Way, Me..."
9,None,None,None,None,None

In [10]:
df.to_csv('data/zillow.csv')

# DWELL STUDENT LIVING NEAR RMIT UNIVERSITY (15 mins walk)

In [11]:
from bs4 import BeautifulSoup
import requests
from csv import writer

url= "https://www.dwellstudent.com.au/melbourne/#rooms"
page = requests.get(url)

In [12]:
soup = BeautifulSoup(page.content, 'html.parser')
lists = soup.find_all('div', class_="col-md-6 item")

with open('housing.csv', 'w', encoding='utf8', newline='') as f:
    thewriter = writer(f)
    header = ['Title', 'Type', 'Price', 'Image']
    thewriter.writerow(header)

    for list in lists:
        title = list.find('div', class_="title")
        type = list.find('div', class_="icon-number") #living, bed, bath numbers
        price = list.find('div', class_="price-wrapper")
        image = list.find('div', class_="img bg-cover-center")
        
        info = [title, type, price, image]
        thewriter.writerow(info)

In [13]:
print(info)

[<div class="title">1 Bedroom Apartment</div>, <div class="icon-number">
<div class="icon living">1</div>
<div class="icon bed">1</div>
<div class="icon bath">1</div>
</div>, <div class="price-wrapper">
<div class="text">From</div>
<div class="price">
                    $529                  </div>
</div>, <div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2019/10/1-Br-Apartment-livingroom-h-768x512.jpg);">
<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2019/10/1-Br-Apartment-livingroom-h-768x512.jpg"/>
</div>]

In [35]:
df = pd.read_csv('housing.csv')
df

,Title,Type,Price,Image
0,"<div class=""title"">5 Bedroom Apartment</div>","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
1,"<div class=""title"">5 Bedroom Apartment Deluxe<...","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
2,"<div class=""title"">4 Bedroom Apartment Deluxe<...","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
3,"<div class=""title"">3 Bedroom Apartment</div>","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
4,"<div class=""title"">3 Bedroom Apartment Large</...","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
5,"<div class=""title"">2 Bedroom Studio</div>","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
6,"<div class=""title"">2 Bedroom Studio with Balco...","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
7,"<div class=""title"">2 Bedroom Apartment</div>","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
8,"<div class=""title"">2 Bedroom Apartment Large</...","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
9,"<div class=""title"">1 Bedroom Suite</div>","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
10,"<div class=""title"">1 Bedroom Studio Deluxe</div>","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
11,"<div class=""title"">1 Bedroom Studio Premium</div>","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
12,"<div class=""title"">1 Bedroom Studio Premium Pl...","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."
13,"<div class=""title"">1 Bedroom Apartment</div>","<div class=""icon-number"">\n<div class=""icon li...","<div class=""price-wrapper"">\n<div class=""text""...","<div class=""img bg-cover-center"" style=""backgr..."

In [38]:
print(f'NUMBER OF CATEGORIES: {df.Image.nunique()}; \n\nUNIQUE NAMES OF THE CATEGORIES {df.Image.unique()}\n\n\n')

NUMBER OF CATEGORIES: 14;

UNIQUE NAMES OF THE CATEGORIES ['<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2020/03/DVMC-5-Bedroom-Thumb-768x432.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2020/03/DVMC-5-Bedroom-Thumb-768x432.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2019/10/5-bed-living-room-600x353-deluxe.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2019/10/5-bed-living-room-600x353-deluxe.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2019/10/4br-apartment-s-view-h-768x512.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2019/10/4br-apartment-s-view-h-768x512.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2020/04/3-bedroom-thumb.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2020/04/3-bedroom-thumb.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2020/03/DVMC-3-Bedroom-Large-Thumb-768x432.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2020/03/DVMC-3-Bedroom-Large-Thumb-768x432.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2019/12/H033rmit-768x512.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2019/12/H033rmit-768x512.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2019/12/H010rmit-768x512.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2019/12/H010rmit-768x512.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2020/03/DVMC-2-Bedroom-Thumb-768x432.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2020/03/DVMC-2-Bedroom-Thumb-768x432.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2021/01/2021-dwellVMC_2BR-Large_IMG_0007-edited.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2021/01/2021-dwellVMC_2BR-Large_IMG_0007-edited.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2020/03/1-br-suite-thumb-768x432.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2020/03/1-br-suite-thumb-768x432.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2020/03/1-br-deluxe-studio-768x494.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2020/03/1-br-deluxe-studio-768x494.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2019/10/1br-studio-h-768x512.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2019/10/1br-studio-h-768x512.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2019/11/1-Bedroom-Studio-Premium-Plus-1-600x400.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2019/11/1-Bedroom-Studio-Premium-Plus-1-600x400.jpg"/>\n</div>'
 '<div class="img bg-cover-center" style="background-image: url(https://www.dwellstudent.com.au/wp-content/uploads/2019/10/1-Br-Apartment-livingroom-h-768x512.jpg);">\n<img class="img-mask" src="https://www.dwellstudent.com.au/wp-content/uploads/2019/10/1-Br-Apartment-livingroom-h-768x512.jpg"/>\n</div>']

In [31]:
df['Title'] = df['Title'].str.replace(r'<[^<>]*>', '', regex=True)
df['Type'] = df['Type'].str.replace(r'<[^<>]*>', '', regex=True)
df['Price'] = df['Price'].str.replace(r'<[^<>]*>', '', regex=True)
# df['Image'] = df['Image'].str.replace(r'<[^<>]*>', '', regex=True)

import re
exp = re.compile(r'(?P<url>https?://[^\s]+)')
df[['Image']] = df['Image'].str.extract(exp, expand=True)

df.to_csv('data/dwell.csv')
df

,Title,Type,Price,Image
0,5 Bedroom Apartment,\n5\n5\n2\n,\nFrom\n\n$389 $285 \n,\n\n
1,5 Bedroom Apartment Deluxe,\n5\n5\n2\n,\nFrom\n\n $345 ...,\n\n
2,4 Bedroom Apartment Deluxe,\n4\n4\n2\n,\nFrom\n\n$372 $320 \n,\n\n
3,3 Bedroom Apartment,\n3\n3\n1\n,\nFrom\n\n$340 $299 \n,\n\n
4,3 Bedroom Apartment Large,\n3\n3\n1\n,\nFrom\n\n $387* ...,\n\n
5,2 Bedroom Studio,\n2\n2\n1\n,\nFrom\n\n $298 ...,\n\n
6,2 Bedroom Studio with Balcony,\n2\n2\n1\n,\nFrom\n\n$310 $229 \n,\n\n
7,2 Bedroom Apartment,\n2\n2\n1\n,\nFrom\n\n$349 $319 \n,\n\n
8,2 Bedroom Apartment Large,\n2\n2\n1\n,\nFrom\n\n $438 ...,\n\n
9,1 Bedroom Suite,\n1-2\n1\n1\n,\nFrom\n\n$429 $369 \n,\n\n
10,1 Bedroom Studio Deluxe,\n1\n1\n1\n,\nFrom\n\n$429 $369 \n,\n\n
11,1 Bedroom Studio Premium,\n1\n1\n1\n,\nFrom\n\n$449 $379 \n,\n\n
12,1 Bedroom Studio Premium Plus,\n1\n1\n1\n,\nFrom\n\n $479 ...,\n\n
13,1 Bedroom Apartment,\n1\n1\n1\n,\nFrom\n\n $529 ...,\n\n